module.exports = [
  // Companions
  {
    name: "Demon Intern",
    rarity: "Mythical",
    cost: 1500,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Angelic Recruit",
    rarity: "Mythical",
    cost: 1500,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Butch",
    rarity: "Mythical",
    cost: 650,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Carty",
    rarity: "Mythical",
    cost: 0,
    exclusive: true,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Cluckles",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Doomling",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Drodo the Druffin",
    rarity: "Mythical",
    cost: 650,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Cate & Doge",
    rarity: "Mythical",
    cost: 3500,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Landshark",
    rarity: "Mythical",
    cost: 300,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Huntling",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Turbo the Turtle",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Itsy",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Janjou the Brave",
    rarity: "Mythical",
    cost: 300,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Krobeling",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Mighty Boar",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Greevil",
    rarity: "Mythical",
    cost: 300,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Nian the Cuddle Beast",
    rarity: "Mythical",
    cost: 1500,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Pangoling",
    rarity: "Mythical",
    cost: 650,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Pudgling",
    rarity: "Mythical",
    cost: 300,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Scotty",
    rarity: "Mythical",
    cost: 650,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Shagbark",
    rarity: "Mythical",
    cost: 300,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Parasight",
    rarity: "Mythical",
    cost: 300,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Shroom Hat",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Icefrog",
    rarity: "Mythical",
    cost: -1,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Llama the Llama",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Tory",
    rarity: "Mythical",
    cost: 300,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Tory the Sky Guardian",
    rarity: "Mythical",
    cost: 650,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Venoling",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
  {
    name: "Choppy the Log Surfer",
    rarity: "Mythical",
    cost: 150,
    type: "companion",
    equip_group: "companion",
  },
];
