module.exports = [
  {
    cost: 0,
    cosmetic_id: "announcer1",
    rarity: "Common",
    type: "Announcer",
    equip_group: "announcer",
  },
  {
    cost: -1,
    cosmetic_id: "border1",
    rarity: "",
    type: "Avatar",
    equip_group: "avatar",
  },
  {
    cost: -1,
    cosmetic_id: "border2",
    rarity: "",
    type: "Avatar",
    equip_group: "avatar",
  },
  {
    cost: -1,
    cosmetic_id: "border3",
    rarity: "",
    type: "Avatar",
    equip_group: "avatar",
  },
  {
    cost: -1,
    cosmetic_id: "border4",
    rarity: "",
    type: "Avatar",
    equip_group: "avatar",
  },
  {
    cost: -1,
    cosmetic_id: "border5",
    rarity: "",
    type: "Avatar",
    equip_group: "avatar",
  },
  {
    cost: -1,
    cosmetic_id: "badge1",
    rarity: "",
    type: "Badge",
    equip_group: "badge",
  },
  {
    cost: -1,
    cosmetic_id: "badge2",
    rarity: "",
    type: "Badge",
    equip_group: "badge",
  },
  {
    cost: -1,
    cosmetic_id: "badge3",
    rarity: "",
    type: "Badge",
    equip_group: "badge",
  },
  {
    cost: -1,
    cosmetic_id: "badge4",
    rarity: "",
    type: "Badge",
    equip_group: "badge",
  },
  {
    cost: -1,
    cosmetic_id: "badge5",
    rarity: "",
    type: "Badge",
    equip_group: "badge",
  },
  {
    cost: -1,
    cosmetic_id: "assault1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_assault",
  },
  {
    cost: -1,
    cosmetic_id: "assault2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_assault",
  },
  {
    cost: -1,
    cosmetic_id: "assault3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_assault",
  },
  {
    cost: -1,
    cosmetic_id: "blink1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_blink",
  },
  {
    cost: -1,
    cosmetic_id: "blink2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_blink",
  },
  {
    cost: -1,
    cosmetic_id: "blink3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_blink",
  },
  {
    cost: -1,
    cosmetic_id: "deny1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "deny",
  },
  {
    cost: -1,
    cosmetic_id: "deny2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "deny",
  },
  {
    cost: -1,
    cosmetic_id: "deny3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "deny",
  },
  {
    cost: -1,
    cosmetic_id: "deny4",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "deny",
  },
  {
    cost: -1,
    cosmetic_id: "deny5",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "deny",
  },
  {
    cost: -1,
    cosmetic_id: "cyclone1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_eul",
  },
  {
    cost: -1,
    cosmetic_id: "cyclone2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_eul",
  },
  {
    cost: -1,
    cosmetic_id: "cyclone3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_eul",
  },
  {
    cost: -1,
    cosmetic_id: "force1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_force",
  },
  {
    cost: -1,
    cosmetic_id: "force2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_force",
  },
  {
    cost: -1,
    cosmetic_id: "force3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_force",
  },
  {
    cost: -1,
    cosmetic_id: "fountain1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "fountain",
  },
  {
    cost: -1,
    cosmetic_id: "fountain2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "fountain",
  },
  {
    cost: -1,
    cosmetic_id: "fountain3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "fountain",
  },
  {
    cost: -1,
    cosmetic_id: "reroll1",
    rarity: "",
    type: "Reroll",
    equip_group: "",
  },
  {
    cost: -1,
    cosmetic_id: "reroll",
    rarity: "",
    type: "Reroll",
    equip_group: "",
  },
  {
    cost: -1,
    cosmetic_id: "reroll2",
    rarity: "",
    type: "Reroll",
    equip_group: "",
  },
  {
    cost: -1,
    cosmetic_id: "greaves1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_greaves",
  },
  {
    cost: -1,
    cosmetic_id: "greaves2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_greaves",
  },
  {
    cost: -1,
    cosmetic_id: "greaves3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_greaves",
  },
  {
    cost: -1,
    cosmetic_id: "levelup1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "levelup",
  },
  {
    cost: -1,
    cosmetic_id: "levelup2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "levelup",
  },
  {
    cost: -1,
    cosmetic_id: "levelup3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "levelup",
  },
  {
    cost: -1,
    cosmetic_id: "mek1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mek",
  },
  {
    cost: -1,
    cosmetic_id: "mek2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mek",
  },
  {
    cost: -1,
    cosmetic_id: "mek3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mek",
  },
  {
    cost: -1,
    cosmetic_id: "mjollnir1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mjollnor",
  },
  {
    cost: -1,
    cosmetic_id: "mjollnir2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mjollnor",
  },
  {
    cost: -1,
    cosmetic_id: "mjollnir3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mjollnor",
  },
  {
    cost: -1,
    cosmetic_id: "picking1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "picking_1",
  },
  {
    cost: -1,
    cosmetic_id: "picking2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "picking_2",
  },
  {
    cost: -1,
    cosmetic_id: "phase1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_phase",
  },
  {
    cost: -1,
    cosmetic_id: "phase2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_phase",
  },
  {
    cost: -1,
    cosmetic_id: "phase3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_phase",
  },
  {
    cost: -1,
    cosmetic_id: "pipe1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_pipe",
  },
  {
    cost: -1,
    cosmetic_id: "pipe2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_pipe",
  },
  {
    cost: -1,
    cosmetic_id: "pipe3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_pipe",
  },
  {
    cost: -1,
    cosmetic_id: "radiance1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_radiance",
  },
  {
    cost: -1,
    cosmetic_id: "radiance2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_radiance",
  },
  {
    cost: -1,
    cosmetic_id: "radiance3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_radiance",
  },
  {
    cost: -1,
    cosmetic_id: "shiva1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "shiva2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "shiva3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "shivaaura1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "shivaaura2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "shivaaura3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "teleport1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_teleport",
  },
  {
    cost: -1,
    cosmetic_id: "teleport2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_teleport",
  },
  {
    cost: -1,
    cosmetic_id: "teleport3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_teleport",
  },
  {
    cost: -1,
    cosmetic_id: "vlads1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_vlads",
  },
  {
    cost: -1,
    cosmetic_id: "vlads2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_vlads",
  },
  {
    cost: -1,
    cosmetic_id: "vlads3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_vlads",
  },
  {
    cost: -1,
    cosmetic_id: "highfive1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "highfive",
  },
  {
    cost: -1,
    cosmetic_id: "highfive2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "highfive",
  },
  {
    cost: -1,
    cosmetic_id: "highfive3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "highfive",
  },
  {
    cost: -1,
    cosmetic_id: "highfive4",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "highfive",
  },
  {
    cost: -1,
    cosmetic_id: "highfive5",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "highfive",
  },
  {
    cost: -1,
    cosmetic_id: "baloon1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon4",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon5",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon6",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon7",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon8",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon9",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon10",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: 200,
    cosmetic_id: "bpaccel1",
    rarity: "",
    type: "BP Accelerator",
    equip_group: "bpaccel",
  },
  {
    cost: 500,
    cosmetic_id: "bpaccel2",
    rarity: "",
    type: "BP Accelerator",
    equip_group: "bpaccel",
  },
  {
    cost: 100,
    cosmetic_id: "chest1",
    rarity: "Common",
    type: "Chest",
    equip_group: "",
  },
  {
    cost: 200,
    cosmetic_id: "chest2",
    rarity: "Uncommon",
    type: "Chest",
    equip_group: "",
  },
  {
    cost: 400,
    cosmetic_id: "chest3",
    rarity: "Rare",
    type: "Chest",
    equip_group: "",
  },
  {
    cost: 1000,
    cosmetic_id: "chest4",
    rarity: "Mythical",
    type: "Chest",
    equip_group: "",
  },
  {
    cost: 2000,
    cosmetic_id: "chest5",
    rarity: "Legendary",
    type: "Chest",
    equip_group: "",
  },
  {
    cost: 150,
    cosmetic_id: "choppy_the_log_surfer",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "cluckles_the_brave",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 120,
    cosmetic_id: "doomling",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "huntling",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "itsy",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "krobeling",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "llama_the_llama",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "mighty_boar",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "shroom_hat",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "turbo_the_turtle",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "venoling",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "greevil",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "janjou",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "landshark",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "parasight",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "pudgling",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "shagbark_the_plush",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "tory",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "butch",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "drodo",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "tenderfoot",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "scotty",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "tory_the_sky_guardian",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 1500,
    cosmetic_id: "angelic_recruit",
    rarity: "Mythical",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 1500,
    cosmetic_id: "demon_intern",
    rarity: "Mythical",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 1500,
    cosmetic_id: "nian_the_cuddle_beast",
    rarity: "Mythical",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 3500,
    cosmetic_id: "baby_roshan",
    rarity: "Legendary",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: -1,
    cosmetic_id: "icefrog",
    rarity: "Ancient",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: -1,
    cosmetic_id: "carty",
    rarity: "Ancient",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 2000,
    cosmetic_id: "spring_haze",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "butterfly_romp",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "felicitys_blessing",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "acid_mist",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "orbital_decay",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "searing_essence",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "winds_of_winter",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "spirit_of_ember",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "touch_of_midas",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "silver_streak",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "bleak_hallucination",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "crystal_rift",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "frostivus_frost",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 4000,
    cosmetic_id: "desert_storm",
    rarity: "Legendary",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "trail_of_the_lotus_blossom",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "oceans_call",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "champions_aura_2014",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 4000,
    cosmetic_id: "ethereal_flame",
    rarity: "Legendary",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 4000,
    cosmetic_id: "star_blaze",
    rarity: "Legendary",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 4000,
    cosmetic_id: "trail_of_burning_doom",
    rarity: "Legendary",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: -3,
    cosmetic_id: "statResetCoupon",
    rarity: "Legendary",
    type: "Other",
    equip_group: "",
  },
  {
    cost: -1,
    cosmetic_id: "xp_coupon_500",
    rarity: "Common",
    type: "Chest XP",
    equip_group: "",
  },
  {
    cost: -1,
    cosmetic_id: "xp_coupon_1000",
    rarity: "Common",
    type: "Chest XP",
    equip_group: "",
  },
  {
    cost: -1,
    cosmetic_id: "xp_coupon_2000",
    rarity: "Uncommon",
    type: "Chest XP",
    equip_group: "",
  },
  {
    cost: -1,
    cosmetic_id: "xp_coupon_5000",
    rarity: "Rare",
    type: "Chest XP",
    equip_group: "",
  },
  {
    cost: -1,
    cosmetic_id: "xp_coupon_10000",
    rarity: "Mythical",
    type: "Chest XP",
    equip_group: "",
  },
  {
    cost: -1,
    cosmetic_id: "xp_coupon_25000",
    rarity: "Legendary",
    type: "Chest XP",
    equip_group: "",
  },
  {
    cost: -2,
    cost_usd: 5,
    cosmetic_id: "xp_1",
    rarity: "Common",
    type: "XP",
    equip_group: "",
  },
  {
    cost: -2,
    cost_usd: 10,
    cosmetic_id: "xp_2",
    rarity: "Uncommon",
    type: "XP",
    equip_group: "",
  },
  {
    cost: -2,
    cost_usd: 20,
    cosmetic_id: "xp_3",
    rarity: "Rare",
    type: "XP",
    equip_group: "",
  },
  {
    cost: -2,
    cost_usd: 50,
    cosmetic_id: "xp_4",
    rarity: "Mythical",
    type: "XP",
    equip_group: "",
  },
  {
    cost: -2,
    cost_usd: 100,
    cosmetic_id: "xp_5",
    rarity: "Legendary",
    type: "XP",
    equip_group: "",
  },
  {
    cost: 100,
    cosmetic_id: "announcer2",
    rarity: "Common",
    type: "Announcer",
    equip_group: "announcer",
  },
  {
    cost: 300,
    cosmetic_id: "huskie",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "captain_bamboo",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "brewling",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "steeljaw",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "coral",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 1500,
    cosmetic_id: "brightjoy",
    rarity: "Mythical",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 2000,
    cosmetic_id: "i_love_you",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: -1,
    cosmetic_id: "emblem1",
    rarity: "Ancient",
    type: "Emblem",
    equip_group: "emblem",
  },
];
