module.exports = [
  {
    cost: 0,
    cosmetic_id: "announcer1",
    rarity: "Common",
    type: "Announcer",
    equip_group: "announcer",
  },
  {
    cost: -1,
    cosmetic_id: "border1",
    rarity: "",
    type: "Avatar",
    equip_group: "avatar",
  },
  {
    cost: -1,
    cosmetic_id: "border2",
    rarity: "",
    type: "Avatar",
    equip_group: "avatar",
  },
  {
    cost: -1,
    cosmetic_id: "border3",
    rarity: "",
    type: "Avatar",
    equip_group: "avatar",
  },
  {
    cost: -1,
    cosmetic_id: "border4",
    rarity: "",
    type: "Avatar",
    equip_group: "avatar",
  },
  {
    cost: -1,
    cosmetic_id: "border5",
    rarity: "",
    type: "Avatar",
    equip_group: "avatar",
  },
  {
    cost: -1,
    cosmetic_id: "badge1",
    rarity: "",
    type: "Badge",
    equip_group: "badge",
  },
  {
    cost: -1,
    cosmetic_id: "badge2",
    rarity: "",
    type: "Badge",
    equip_group: "badge",
  },
  {
    cost: -1,
    cosmetic_id: "badge3",
    rarity: "",
    type: "Badge",
    equip_group: "badge",
  },
  {
    cost: -1,
    cosmetic_id: "badge4",
    rarity: "",
    type: "Badge",
    equip_group: "badge",
  },
  {
    cost: -1,
    cosmetic_id: "badge5",
    rarity: "",
    type: "Badge",
    equip_group: "badge",
  },
  {
    cost: -1,
    cosmetic_id: "assault1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_assault",
  },
  {
    cost: -1,
    cosmetic_id: "assault2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_assault",
  },
  {
    cost: -1,
    cosmetic_id: "assault3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_assault",
  },
  {
    cost: -1,
    cosmetic_id: "blink1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_blink",
  },
  {
    cost: -1,
    cosmetic_id: "blink2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_blink",
  },
  {
    cost: -1,
    cosmetic_id: "blink3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_blink",
  },
  {
    cost: -1,
    cosmetic_id: "deny1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "deny",
  },
  {
    cost: -1,
    cosmetic_id: "deny2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "deny",
  },
  {
    cost: -1,
    cosmetic_id: "deny3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "deny",
  },
  {
    cost: -1,
    cosmetic_id: "deny4",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "deny",
  },
  {
    cost: -1,
    cosmetic_id: "deny5",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "deny",
  },
  {
    cost: -1,
    cosmetic_id: "cyclone1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_eul",
  },
  {
    cost: -1,
    cosmetic_id: "cyclone2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_eul",
  },
  {
    cost: -1,
    cosmetic_id: "cyclone3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_eul",
  },
  {
    cost: -1,
    cosmetic_id: "force1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_force",
  },
  {
    cost: -1,
    cosmetic_id: "force2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_force",
  },
  {
    cost: -1,
    cosmetic_id: "force3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_force",
  },
  {
    cost: -1,
    cosmetic_id: "fountain1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "fountain",
  },
  {
    cost: -1,
    cosmetic_id: "fountain2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "fountain",
  },
  {
    cost: -1,
    cosmetic_id: "fountain3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "fountain",
  },
  {
    cost: -1,
    cosmetic_id: "greaves1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_greaves",
  },
  {
    cost: -1,
    cosmetic_id: "greaves2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_greaves",
  },
  {
    cost: -1,
    cosmetic_id: "greaves3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_greaves",
  },
  {
    cost: -1,
    cosmetic_id: "levelup1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "levelup",
  },
  {
    cost: -1,
    cosmetic_id: "levelup2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "levelup",
  },
  {
    cost: -1,
    cosmetic_id: "levelup3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "levelup",
  },
  {
    cost: -1,
    cosmetic_id: "mek1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mek",
  },
  {
    cost: -1,
    cosmetic_id: "mek2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mek",
  },
  {
    cost: -1,
    cosmetic_id: "mek3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mek",
  },
  {
    cost: -1,
    cosmetic_id: "mjollnir1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mjollnor",
  },
  {
    cost: -1,
    cosmetic_id: "mjollnir2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mjollnor",
  },
  {
    cost: -1,
    cosmetic_id: "mjollnir3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_mjollnor",
  },
  {
    cost: -1,
    cosmetic_id: "picking1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "picking_1",
  },
  {
    cost: -2,
    cosmetic_id: "picking2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "picking_2",
  },
  {
    cost: -1,
    cosmetic_id: "phase1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_phase",
  },
  {
    cost: -1,
    cosmetic_id: "phase2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_phase",
  },
  {
    cost: -1,
    cosmetic_id: "phase3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_phase",
  },
  {
    cost: -1,
    cosmetic_id: "pipe1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_pipe",
  },
  {
    cost: -1,
    cosmetic_id: "pipe2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_pipe",
  },
  {
    cost: -1,
    cosmetic_id: "pipe3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_pipe",
  },
  {
    cost: -1,
    cosmetic_id: "radiance1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_radiance",
  },
  {
    cost: -1,
    cosmetic_id: "radiance2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_radiance",
  },
  {
    cost: -1,
    cosmetic_id: "radiance3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_radiance",
  },
  {
    cost: -1,
    cosmetic_id: "shiva1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "shiva2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "shiva3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "shivaaura1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "shivaaura2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "shivaaura3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_shiva",
  },
  {
    cost: -1,
    cosmetic_id: "teleport1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_teleport",
  },
  {
    cost: -1,
    cosmetic_id: "teleport2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_teleport",
  },
  {
    cost: -1,
    cosmetic_id: "teleport3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_fx_teleport",
  },
  {
    cost: -1,
    cosmetic_id: "vlads1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_vlads",
  },
  {
    cost: -1,
    cosmetic_id: "vlads2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_vlads",
  },
  {
    cost: -1,
    cosmetic_id: "vlads3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "item_aura_vlads",
  },
  {
    cost: -1,
    cosmetic_id: "highfive1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "highfive",
  },
  {
    cost: -1,
    cosmetic_id: "highfive2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "highfive",
  },
  {
    cost: -1,
    cosmetic_id: "highfive3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "highfive",
  },
  {
    cost: -1,
    cosmetic_id: "highfive4",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "highfive",
  },
  {
    cost: -1,
    cosmetic_id: "highfive5",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "highfive",
  },
  {
    cost: -1,
    cosmetic_id: "baloon1",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon2",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon3",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon4",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon5",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon6",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon7",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon8",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon9",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: -1,
    cosmetic_id: "baloon10",
    rarity: "",
    type: "Battlepass FX",
    equip_group: "balloon",
  },
  {
    cost: 200,
    cosmetic_id: "bpaccel1",
    rarity: "",
    type: "BP Accelerator",
    equip_group: "bpaccel",
  },
  {
    cost: 500,
    cosmetic_id: "bpaccel2",
    rarity: "",
    type: "BP Accelerator",
    equip_group: "bpaccel",
  },
  {
    cost: 100,
    cosmetic_id: "chest1",
    rarity: "Common",
    type: "Chest",
    equip_group: "",
  },
  {
    cost: 200,
    cosmetic_id: "chest2",
    rarity: "Uncommon",
    type: "Chest",
    equip_group: "",
  },
  {
    cost: 400,
    cosmetic_id: "chest3",
    rarity: "Rare",
    type: "Chest",
    equip_group: "",
  },
  {
    cost: 1000,
    cosmetic_id: "chest4",
    rarity: "Mythical",
    type: "Chest",
    equip_group: "",
  },
  {
    cost: 2000,
    cosmetic_id: "chest5",
    rarity: "Legendary",
    type: "Chest",
    equip_group: "",
  },
  {
    cost: -2,
    cosmetic_id: "companion1",
    rarity: "Ancient",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion2",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion3",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion4",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion5",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion6",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion7",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion8",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion9",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion10",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion11",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 150,
    cosmetic_id: "companion12",
    rarity: "Common",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 3500,
    cosmetic_id: "companion13",
    rarity: "Legendary",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: -3,
    cosmetic_id: "companion14",
    rarity: "Legendary",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 1500,
    cosmetic_id: "companion15",
    rarity: "Mythical",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 1500,
    cosmetic_id: "companion16",
    rarity: "Mythical",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 1500,
    cosmetic_id: "companion17",
    rarity: "Mythical",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "companion18",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "companion19",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "companion20",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "companion21",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 650,
    cosmetic_id: "companion22",
    rarity: "Rare",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "companion23",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "companion24",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "companion25",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "companion26",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "companion27",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "companion28",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 300,
    cosmetic_id: "companion29",
    rarity: "Uncommon",
    type: "Companion",
    equip_group: "companion",
  },
  {
    cost: 800,
    cosmetic_id: "companionfx1",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "companionfx2",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "companionfx3",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "companionfx4",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "companionfx5",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "companionfx6",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "companionfx7",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "companionfx8",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "companionfx9",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 800,
    cosmetic_id: "companionfx10",
    rarity: "Rare",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "companionfx11",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "companionfx12",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "companionfx13",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "companionfx14",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "companionfx15",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 2000,
    cosmetic_id: "companionfx16",
    rarity: "Mythical",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 4000,
    cosmetic_id: "companionfx17",
    rarity: "Legendary",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 4000,
    cosmetic_id: "companionfx18",
    rarity: "Legendary",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 4000,
    cosmetic_id: "companionfx19",
    rarity: "Legendary",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: 4000,
    cosmetic_id: "companionfx20",
    rarity: "Legendary",
    type: "Companion FX",
    equip_group: "companion_fx",
  },
  {
    cost: -3,
    cosmetic_id: "statResetCoupon",
    rarity: "Legendary",
    type: "Other",
    equip_group: "",
  },
];
