module.exports = [
  {
    cost_usd: 5,
    item_id: "xp_1",
    type: "XP",
    reward: 10000,
  },
  {
    cost_usd: 10,
    item_id: "xp_2",
    type: "XP",
    reward: 25000,
  },
  {
    cost_usd: 20,
    item_id: "xp_3",
    type: "XP",
    reward: 60000,
  },
  {
    cost_usd: 50,
    item_id: "xp_4",
    type: "XP",
    reward: 175000,
  },
  {
    cost_usd: 100,
    item_id: "xp_5",
    type: "XP",
    reward: 400000,
  },
  {
    item_id: "poggers_1",
    type: "POGGERS",
    cost_usd: 1,
    reward: 100,
  },
  {
    item_id: "poggers_2",
    type: "POGGERS",
    cost_usd: 5,
    reward: 550,
  },
  {
    item_id: "poggers_3",
    type: "POGGERS",
    cost_usd: 10,
    reward: 1150,
  },
  {
    item_id: "poggers_4",
    type: "POGGERS",
    cost_usd: 20,
    reward: 2400,
  },
  {
    item_id: "poggers_5",
    type: "POGGERS",
    cost_usd: 50,
    reward: 6500,
  },
  {
    item_id: "poggers_6",
    type: "POGGERS",
    cost_usd: 100,
    reward: 15000,
  },

  {
    cost_usd: 2,
    item_id: "bp_1_1",
    type: "BP1",
    reward: 1,
  },
  {
    cost_usd: 10.8,
    item_id: "bp_1_6",
    type: "BP1",
    reward: 6,
  },
  {
    cost_usd: 19.2,
    item_id: "bp_1_12",
    type: "BP1",
    reward: 12,
  },
  {
    cost_usd: 5,
    item_id: "bp_2_1",
    type: "BP2",
    reward: 1,
  },
  {
    cost_usd: 27,
    item_id: "bp_2_6",
    type: "BP2",
    reward: 6,
  },
  {
    cost_usd: 48,
    item_id: "bp_2_12",
    type: "BP2",
    reward: 12,
  },
  {
    cost_usd: 15,
    item_id: "bp_3_1",
    type: "BP3",
    reward: 1,
  },
  {
    cost_usd: 81,
    item_id: "bp_3_6",
    type: "BP3",
    reward: 6,
  },
  {
    cost_usd: 144,
    item_id: "bp_3_12",
    type: "BP3",
    reward: 12,
  },
];
