const sampleData = {
  gameStats: {
    gameDuration: "1249", // seconds from horn
    cheatsEnabled: "false",
    rankedGame: "true",
    winnerTeam: "DOTA_TEAM_GOODGUYS", // DOTA_TEAM_GOODGUYS = 2 (Lorekeepers), DOTA_TEAM_BADGUYS = 3 (Flameguard)
    healthDrops: "28",
    bannedHeroes: [
      // anything between 0 and 6 banned heroes
      "npc_dota_hero_antimage",
      "npc_dota_hero_batrider",
      "npc_dota_hero_keeper_of_the_light",
    ],
    teamInfo: {
      DOTA_TEAM_GOODGUYS: {
        kills: "37",
        deaths: "28",
        assists: "51",
        guardianKills: {
          // can be null. time of kill: guardian killed. POG_GUARDIAN_CREEPS = 1 (monkey), POG_GUARDIAN_DAMAGE = 2 (pooky), POG_GUARDIAN_CDR = 3 (bucket)
          "531": "POG_GUARDIAN_CREEPS",
          "569": "POG_GUARDIAN_DAMAGE",
        },
        buildingKills: {
          // can be null. structure: kill time.
          firstTower: "181",
          secondTower: "290",
          barracks: "617",
          thirdTower: "772",
          fourthTower: "788",
        },
      },
      DOTA_TEAM_BADGUYS: {
        kills: "28",
        deaths: "37",
        assists: "40",
        guardianKills: {},
        buildingKills: {
          firstTower: "315",
          secondTower: "342",
        },
      },
    },
    playerInfo: {
      "1": {
        steamid: "76561197960956468", // steam64 ID
        username: "Dingleberry", // steam username
        team: "DOTA_TEAM_GOODGUYS",
        banChoice: "npc_dota_hero_batrider", // can be null
        availablePicks: [
          "npc_dota_hero_lina",
          "npc_dota_hero_slark",
          "npc_dota_hero_scaldris",
        ],
        rerolledHeroes: [
          // can be null
          "npc_dota_hero_spectre",
        ],
        finalPick: "npc_dota_hero_lina",
        kills: "8",
        deaths: "11",
        assists: "16",
        lastHits: "168",
        denies: "3",
        doubleKills: "3",
        rampages: "1",
        heroDamage: "16238",
        buildingDamage: "1281",
        heroHealing: "234",
        tpScrollsUsed: "9",
        runesUsed: "3", // counts on activation, not pickup (in bottle's case)
        healthDropDuration: "127", // total duration of the regeneration buff on this hero
        currentGold: "1111",
        totalGold: "21357",
        totalExp: "19822",
        level: "24",
        spentRerolls: "1",
        neutralItems: 1,
        healingGoblets: 1,
        highFives: 0,
        abilities: {
          // ability name: final level (includes talents)
          lina_dragon_slave: "4",
          lina_light_strike_array: "4",
          lina_fiery_soul: "4",
          lina_laguna_blade: "3",
          special_ability_damage_30: "1",
          special_ability_spell_amp_12: "1",
          special_ability_mana_regen_3: "1",
        },
        itemPurchases: {
          // item purchases throughout the game, time: item name
          "34": "item_blink",
          "42": "item_cyclone",
          "111": "item_sheepstick",
          "234": "item_phase_boots",
          "456": "item_nokrash_blade",
          "799": "item_sphere",
          "919": "item_mango",
          "1028": "item_refresher",
        },
        finalInventory: {
          // end-of-match inventory, 0-5 = active inventory, 6-8 = backpack
          "0": "item_blink",
          "1": "item_cyclone",
          "2": "item_sheepstick",
          "3": "item_phase_boots",
          "4": "item_nokrash_blade",
          "5": "item_sphere",
          "6": "item_mango",
          "7": "item_refresher",
        },
        permanentBuffs: [
          // can be null. tracks permanent buffs like flesh heap, edible aghs, and moon shard
          "modifier_moon_shard_consumed",
          "modifier_ultimate_scepter_consumed",
        ],
        disconnectEvents: {
          // can be null if the player never disconnected until the end of the game. disconnect time: reconnect time (-1 if the player never reconnected after this disconnect event). Counts anything before the horn as 0.
          "37": "45",
          "871": "-1",
        },
        abandoned: "false",
      },
      "2": {
        // I'll omit other players for brevity but there should always be 6 of them
        steamid: "76561198007141460",
        username: "MidAndFeed",
        team: "DOTA_TEAM_BADGUYS",
        banChoice: "npc_dota_hero_antimage",
        availablePicks: [
          "npc_dota_hero_tidehunter",
          "npc_dota_hero_lich",
          "npc_dota_hero_mifune",
        ],
        rerolledHeroes: ["npc_dota_hero_warlock"],
        finalPick: "npc_dota_hero_mifune",
        kills: "8",
        deaths: "11",
        assists: "16",
        lastHits: "168",
        denies: "3",
        doubleKills: "1",
        rampages: "0",
        heroDamage: "16238",
        buildingDamage: "1281",
        heroHealing: "234",
        tpScrollsUsed: "9",
        runesUsed: "1",
        healthDropDuration: "89",
        currentGold: "322",
        totalGold: "21357",
        totalExp: "19822",
        level: "24",
        spentRerolls: "3",
        neutralItems: 1,
        healingGoblets: 1,
        highFives: 0,
        abilities: {
          lina_dragon_slave: "4",
          lina_light_strike_array: "4",
          lina_fiery_soul: "4",
          lina_laguna_blade: "3",
          special_ability_damage_30: "1",
          special_ability_spell_amp_12: "1",
          special_ability_mana_regen_3: "1",
        },
        itemPurchases: {
          "34": "item_blink",
          "42": "item_cyclone",
          "111": "item_sheepstick",
          "234": "item_phase_boots",
          "456": "item_nokrash_blade",
          "799": "item_rapier",
          "919": "item_mango",
          "1028": "item_refresher",
        },
        finalInventory: {
          "0": "item_blink",
          "1": "item_cyclone",
          "2": "item_sheepstick",
          "3": "item_phase_boots",
          "4": "item_nokrash_blade",
          "5": "item_sphere",
          "6": "item_mango",
          "7": "item_refresher",
          "8": "item_heart",
          "9": "item_tango",
        },
        permanentBuffs: [],
        disconnectEvents: {
          "422": "469",
        },
        abandoned: "true",
      },
    },
  },
};

const realSample = {
  healthDrops: 30,
  winnerTeam: "DOTA_TEAM_BADGUYS",
  gameDuration: 779.11999511719,
  teamInfo: {
    DOTA_TEAM_BADGUYS: {
      buildingKills: {
        barracks: 609.66137695312,
        thirdTower: 671.81286621094,
        secondTower: 581.90148925781,
        fourthTower: 683.7099609375,
        firstTower: 459.7646484375,
      },
      assists: 42,
      guardianKills: [],
      kills: 25,
      deaths: 9,
    },
    DOTA_TEAM_GOODGUYS: {
      buildingKills: [],
      assists: 17,
      guardianKills: [],
      kills: 6,
      deaths: 25,
    },
  },
  playerInfo: {
    "0": {
      assists: 10,
      availablePicks: [
        "npc_dota_hero_night_stalker",
        "npc_dota_hero_bloodseeker",
        "npc_dota_hero_shredder",
        "npc_dota_hero_bane",
      ],
      finalPick: "npc_dota_hero_night_stalker",
      denies: 0,
      totalGold: 28793,
      team: "DOTA_TEAM_BADGUYS",
      heroDamage: 25936,
      totalExp: 28785,
      itemPurchases: {
        "0": "item_magic_stick",
        "1": "item_branches",
        "2": "item_branches",
        "3": "item_recipe_magic_wand",
        "4": "item_ward_observer",
        "5": "item_ward_sentry",
        "128": "item_boots",
        "130": "item_point_booster",
        "191": "item_ogre_axe",
        "216": "item_blade_of_alacrity",
        "279": "item_staff_of_wizardry",
        "341": "item_chainmail",
        "342": "item_blades_of_attack",
        "399": "item_mithril_hammer",
        "400": "item_belt_of_strength",
        "401": "item_recipe_basher",
        "467": "item_ring_of_health",
        "468": "item_vitality_booster",
        "496": "item_recipe_abyssal_blade",
        "543": "item_blight_stone",
        "544": "item_mithril_hammer",
        "681": "item_mithril_hammer",
        "682": "item_recipe_desolator_2",
        "763": "item_pirate_hat",
      },
      runesUsed: 0,
      abandoned: false,
      abilities: {
        night_stalker_void: 4,
        ability_capture: 1,
        generic_hidden: 0,
        night_stalker_hunter_in_the_night: 4,
        special_bonus_unique_night_stalker: 1,
        night_stalker_crippling_fear: 4,
        special_bonus_hp_150: 1,
        night_stalker_darkness: 3,
        special_bonus_unique_night_stalker_2: 0,
        special_bonus_attack_damage_35: 1,
        special_bonus_mp_150: 0,
        special_bonus_strength_12: 0,
        special_bonus_movement_speed_30: 0,
        special_bonus_lifesteal_20: 1,
      },
      finalInventory: {
        "0": "item_magic_wand",
        "1": "item_pog_phase_boots",
        "2": "item_abyssal_blade",
        "3": "item_ultimate_scepter",
        "4": "item_desolator_2",
      },
      steamid: "76561198015195815",
      healthDropDuration: 84.566528320312,
      tpScrollsUsed: 5,
      lastHits: 82,
      buildingDamage: 7599,
      level: 29,
      banChoice: "npc_dota_hero_ember_spirit",
      rerolledHeroes: [],
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 3543,
      neutralItems: 1,
      highFives: 0,
      healingGoblets: 13,
      deaths: 1,
      doubleKills: 3,
      kills: 13,
      username: "ton",
      rampages: 2,
      spentRerolls: 0,
    },
    "1": {
      assists: 14,
      availablePicks: [
        "npc_dota_hero_sand_king",
        "npc_dota_hero_puck",
        "npc_dota_hero_antimage",
        "npc_dota_hero_sniper",
        "npc_dota_hero_riki",
      ],
      finalPick: "npc_dota_hero_sand_king",
      denies: 1,
      totalGold: 26068,
      team: "DOTA_TEAM_BADGUYS",
      heroDamage: 15696,
      totalExp: 15925,
      itemPurchases: {
        "0": "item_magic_stick",
        "1": "item_branches",
        "2": "item_branches",
        "3": "item_recipe_magic_wand",
        "4": "item_ward_sentry",
        "5": "item_ward_sentry",
        "84": "item_boots",
        "118": "item_energy_booster",
        "140": "item_sobi_mask",
        "141": "item_recipe_ring_of_basilius",
        "157": "item_ward_sentry",
        "158": "item_ward_sentry",
        "159": "item_ward_observer",
        "177": "item_crown",
        "216": "item_recipe_veil_of_discord",
        "231": "item_ward_observer",
        "232": "item_ward_sentry",
        "302": "item_point_booster",
        "329": "item_ogre_axe",
        "333": "item_ward_observer",
        "334": "item_ward_sentry",
        "357": "item_staff_of_wizardry",
        "397": "item_blade_of_alacrity",
        "411": "item_ward_sentry",
        "459": "item_ogre_axe",
        "460": "item_staff_of_wizardry",
        "461": "item_ring_of_regen",
        "462": "item_sobi_mask",
        "484": "item_pog_blink",
        "586": "item_recipe_fallen_sky",
        "705": "item_mystic_staff",
        "708": "item_point_booster",
        "709": "item_vitality_booster",
        "740": "item_energy_booster",
        "774": "item_ring_of_regen",
        "775": "item_recipe_headdress",
        "776": "item_chainmail",
        "777": "item_recipe_pog_mekansm",
      },
      runesUsed: 0,
      abandoned: false,
      abilities: {
        special_bonus_unique_sand_king_5: 1,
        sandking_sand_storm: 4,
        special_bonus_hp_175: 1,
        generic_hidden: 0,
        sandking_caustic_finale: 4,
        special_bonus_hp_regen_40: 0,
        special_bonus_unique_sand_king_4: 1,
        ability_capture: 1,
        sandking_epicenter: 3,
        special_bonus_unique_sand_king_2: 1,
        special_bonus_unique_sand_king: 0,
        special_bonus_armor_8: 0,
        special_bonus_unique_sand_king_3: 0,
        sandking_burrowstrike: 4,
      },
      finalInventory: {
        "0": "item_fallen_sky",
        "1": "item_arcane_boots",
        "2": "item_veil_of_discord",
        "3": "item_octarine_core",
        "4": "item_ultimate_scepter",
      },
      steamid: "76561198354330533",
      healthDropDuration: 49,
      tpScrollsUsed: 7,
      lastHits: 54,
      buildingDamage: 3349,
      level: 27,
      banChoice: "npc_dota_hero_silencer",
      rerolledHeroes: ["npc_dota_hero_antimage"],
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 755,
      neutralItems: 1,
      highFives: 0,
      healingGoblets: 7,
      deaths: 5,
      doubleKills: 1,
      kills: 5,
      username: "Lyan",
      rampages: 0,
      spentRerolls: 0,
    },
    "2": {
      assists: 5,
      availablePicks: [
        "npc_dota_hero_keeper_of_the_light",
        "npc_dota_hero_templar_assassin",
        "npc_dota_hero_huskar",
        "npc_dota_hero_slark",
      ],
      finalPick: "npc_dota_hero_templar_assassin",
      denies: 0,
      totalGold: 16714,
      team: "DOTA_TEAM_GOODGUYS",
      heroDamage: 24604,
      totalExp: 17188,
      itemPurchases: {
        "0": "item_magic_stick",
        "1": "item_branches",
        "2": "item_branches",
        "3": "item_recipe_magic_wand",
        "4": "item_branches",
        "5": "item_branches",
        "6": "item_branches",
        "176": "item_mithril_hammer",
        "177": "item_blight_stone",
        "298": "item_mithril_hammer",
        "312": "item_boots",
        "397": "item_gloves",
        "398": "item_belt_of_strength",
        "417": "item_ogre_axe",
        "458": "item_boots_of_elves",
        "459": "item_boots_of_elves",
        "587": "item_staff_of_wizardry",
        "588": "item_ring_of_regen",
        "589": "item_recipe_force_staff",
        "590": "item_recipe_hurricane_pike",
      },
      runesUsed: 0,
      abandoned: false,
      abilities: {
        ability_capture: 1,
        templar_assassin_trap: 3,
        templar_assassin_meld: 4,
        templar_assassin_trap_teleport: 3,
        templar_assassin_psi_blades: 4,
        special_bonus_attack_speed_15: 1,
        special_bonus_unique_templar_assassin: 0,
        special_bonus_unique_templar_assassin_2: 0,
        templar_assassin_psionic_trap: 3,
        special_bonus_movement_speed_15: 0,
        templar_assassin_refraction: 4,
        special_bonus_unique_templar_assassin_4: 1,
        special_bonus_unique_templar_assassin_7: 1,
        special_bonus_unique_templar_assassin_3: 0,
        special_bonus_evasion_15: 1,
      },
      finalInventory: {
        "0": "item_power_treads",
        "1": "item_hurricane_pike",
        "2": "item_branches",
        "3": "item_magic_wand",
        "4": "item_desolator",
        "5": "item_branches",
      },
      steamid: "76561198245667404",
      healthDropDuration: 42,
      tpScrollsUsed: 5,
      lastHits: 54,
      buildingDamage: 0,
      level: 26,
      banChoice: "npc_dota_hero_tinker",
      rerolledHeroes: [],
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 6109,
      neutralItems: 0,
      highFives: 0,
      healingGoblets: 6,
      deaths: 9,
      doubleKills: 1,
      kills: 2,
      username: "[AK]Servando",
      rampages: 0,
      spentRerolls: 0,
    },
    "3": {
      assists: 6,
      availablePicks: [
        "npc_dota_hero_legion_commander",
        "npc_dota_hero_pudge",
        "npc_dota_hero_wisp",
        "npc_dota_hero_dazzle",
      ],
      finalPick: "npc_dota_hero_legion_commander",
      denies: 0,
      totalGold: 15752,
      team: "DOTA_TEAM_GOODGUYS",
      heroDamage: 13651,
      totalExp: 16921,
      itemPurchases: {
        "0": "item_boots",
        "69": "item_magic_stick",
        "70": "item_branches",
        "71": "item_branches",
        "72": "item_recipe_magic_wand",
        "296": "item_mithril_hammer",
        "297": "item_blight_stone",
        "299": "item_ward_observer",
        "300": "item_ward_sentry",
        "357": "item_mithril_hammer",
        "421": "item_javelin",
        "457": "item_gloves",
        "458": "item_belt_of_strength",
        "539": "item_mithril_hammer",
        "640": "item_platemail",
        "690": "item_hyperstone",
        "691": "item_ring_of_protection",
        "692": "item_recipe_buckler",
        "693": "item_recipe_pog_assault",
      },
      runesUsed: 0,
      abandoned: false,
      highFives: 0,
      finalInventory: {
        "0": "item_power_treads",
        "1": "item_desolator",
        "2": "item_pog_maelstrom",
        "3": "item_pog_assault",
        "4": "item_magic_wand",
      },
      steamid: "76561198137743377",
      healthDropDuration: 37.666015625,
      tpScrollsUsed: 5,
      buildingDamage: 0,
      level: 26,
      abilities: {
        special_bonus_mp_regen_150: 0,
        legion_commander_press_the_attack: 4,
        ability_capture: 1,
        generic_hidden: 0,
        special_bonus_strength_7: 1,
        legion_commander_overwhelming_odds: 4,
        special_bonus_unique_legion_commander_5: 0,
        special_bonus_unique_legion_commander: 1,
        special_bonus_unique_legion_commander_6: 1,
        special_bonus_attack_speed_25: 0,
        special_bonus_unique_legion_commander_3: 0,
        legion_commander_duel: 3,
        special_bonus_movement_speed_30: 1,
        legion_commander_moment_of_courage: 4,
      },
      kills: 1,
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 1680,
      currentGold: 2030,
      doubleKills: 0,
      neutralItems: 0,
      healingGoblets: 6,
      deaths: 8,
      rerolledHeroes: [],
      spentRerolls: 0,
      username: "Kanilla",
      rampages: 0,
      lastHits: 35,
    },
    "4": {
      assists: 6,
      availablePicks: [
        "npc_dota_hero_dark_willow",
        "npc_dota_hero_shadow_demon",
        "npc_dota_hero_faceless_void",
        "npc_dota_hero_furion",
      ],
      finalPick: "npc_dota_hero_faceless_void",
      denies: 1,
      totalGold: 17119,
      team: "DOTA_TEAM_GOODGUYS",
      heroDamage: 9129,
      totalExp: 16597,
      itemPurchases: {
        "0": "item_magic_stick",
        "1": "item_branches",
        "2": "item_branches",
        "3": "item_recipe_magic_wand",
        "4": "item_quelling_blade",
        "187": "item_ring_of_health",
        "188": "item_void_stone",
        "194": "item_gloves",
        "259": "item_broadsword",
        "313": "item_mithril_hammer",
        "358": "item_broadsword",
        "409": "item_lifesteal",
        "445": "item_quarterstaff",
        "501": "item_javelin",
        "506": "item_boots",
        "507": "item_belt_of_strength",
        "607": "item_demon_edge",
        "627": "item_quarterstaff",
        "700": "item_javelin",
        "708": "item_broadsword",
        "709": "item_blades_of_attack",
        "710": "item_recipe_lesser_crit",
        "755": "item_demon_edge",
        "756": "item_recipe_greater_crit",
      },
      runesUsed: 0,
      abandoned: false,
      highFives: 0,
      finalInventory: {
        "0": "item_power_treads",
        "1": "item_bfury",
        "2": "item_monkey_king_bar",
        "3": "item_mask_of_madness",
        "4": "item_magic_wand",
        "5": "item_greater_crit",
      },
      steamid: "76561198305781738",
      healthDropDuration: 41.031860351562,
      tpScrollsUsed: 6,
      buildingDamage: 0,
      level: 26,
      abilities: {
        special_bonus_attack_speed_40: 1,
        special_bonus_unique_faceless_void: 0,
        faceless_void_time_dilation: 4,
        faceless_void_time_lock: 4,
        faceless_void_time_walk: 4,
        special_bonus_attack_damage_12: 1,
        ability_capture: 1,
        special_bonus_unique_faceless_void_5: 0,
        faceless_void_chronosphere: 3,
        special_bonus_unique_faceless_void_2: 1,
        special_bonus_unique_faceless_void_3: 1,
        special_bonus_unique_faceless_void_4: 0,
        generic_hidden: 0,
        special_bonus_strength_8: 0,
      },
      kills: 3,
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 169,
      doubleKills: 0,
      neutralItems: 0,
      healingGoblets: 7,
      deaths: 8,
      rerolledHeroes: [],
      spentRerolls: 0,
      username: "MM!!",
      rampages: 0,
      lastHits: 83,
    },
    "5": {
      assists: 18,
      availablePicks: [
        "npc_dota_hero_mars",
        "npc_dota_hero_bounty_hunter",
        "npc_dota_hero_shadow_shaman",
        "npc_dota_hero_enigma",
        "npc_dota_hero_bristleback",
      ],
      finalPick: "npc_dota_hero_bristleback",
      denies: 0,
      totalGold: 28329,
      team: "DOTA_TEAM_BADGUYS",
      heroDamage: 35957,
      totalExp: 36399,
      itemPurchases: {
        "0": "item_magic_stick",
        "1": "item_branches",
        "2": "item_branches",
        "3": "item_recipe_magic_wand",
        "4": "item_smoke_of_deceit",
        "5": "item_ward_observer",
        "85": "item_helm_of_iron_will",
        "219": "item_ring_of_health",
        "220": "item_vitality_booster",
        "221": "item_recipe_crimson_guard",
        "357": "item_boots",
        "366": "item_chainmail",
        "367": "item_blades_of_attack",
        "375": "item_chainmail",
        "376": "item_sobi_mask",
        "377": "item_blight_stone",
        "378": "item_wind_lace",
        "527": "item_ultimate_orb",
        "528": "item_recipe_solar_crest",
        "530": "item_mystic_staff",
        "531": "item_vitality_booster",
        "532": "item_energy_booster",
        "533": "item_point_booster",
        "678": "item_ring_of_health",
        "679": "item_void_stone",
        "680": "item_platemail",
        "681": "item_energy_booster",
      },
      runesUsed: 0,
      abandoned: false,
      abilities: {
        special_bonus_unique_bristleback: 1,
        special_bonus_unique_bristleback_3: 1,
        bristleback_bristleback: 4,
        generic_hidden: 0,
        ability_capture: 1,
        special_bonus_unique_bristleback_2: 1,
        special_bonus_hp_regen_20: 1,
        bristleback_viscous_nasal_goo: 4,
        special_bonus_hp_200: 1,
        bristleback_quill_spray: 4,
        special_bonus_spell_lifesteal_13: 1,
        bristleback_warpath: 3,
        special_bonus_movement_speed_15: 1,
        special_bonus_mp_regen_250: 1,
      },
      finalInventory: {
        "0": "item_solar_crest",
        "1": "item_lotus_orb",
        "2": "item_pog_phase_boots",
        "3": "item_magic_wand",
        "4": "item_crimson_guard",
        "5": "item_octarine_core",
      },
      steamid: "76561198044129222",
      healthDropDuration: 80.3974609375,
      tpScrollsUsed: 5,
      lastHits: 94,
      buildingDamage: 6969,
      level: 30,
      banChoice: "npc_dota_hero_naga_siren",
      rerolledHeroes: ["npc_dota_hero_bounty_hunter"],
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 7171,
      neutralItems: 0,
      highFives: 0,
      healingGoblets: 12,
      deaths: 3,
      doubleKills: 0,
      kills: 7,
      username: "-Scty.Franco",
      rampages: 0,
      spentRerolls: 0,
    },
  },
  cheatsEnabled: false,
  bannedHeroes: [
    "npc_dota_hero_naga_siren",
    "npc_dota_hero_ancient_apparition",
    "npc_dota_hero_ember_spirit",
    "npc_dota_hero_invoker",
    "npc_dota_hero_silencer",
    "npc_dota_hero_tinker",
  ],
  rankedGame: true,
};

const testSample = {
  healthDrops: 43,
  winnerTeam: "DOTA_TEAM_GOODGUYS",
  gameDuration: 947.82751464844,
  teamInfo: {
    DOTA_TEAM_BADGUYS: {
      buildingKills: [],
      assists: 9,
      guardianKills: [],
      kills: 6,
      deaths: 31,
    },
    DOTA_TEAM_GOODGUYS: {
      buildingKills: {
        barracks: 848.18518066406,
        thirdTower: 934.6640625,
        secondTower: 816.85949707031,
        fourthTower: 940.06274414062,
        firstTower: 526.46374511719,
      },
      assists: 46,
      guardianKills: { "901": "POG_GUARDIAN_CREEPS" },
      kills: 31,
      deaths: 6,
    },
  },
  playerInfo: {
    "0": {
      assists: 17,
      availablePicks: [
        "npc_dota_hero_shadow_demon",
        "npc_dota_hero_lich",
        "npc_dota_hero_meepo",
        "npc_dota_hero_weaver",
        "npc_dota_hero_oracle",
      ],
      finalPick: "npc_dota_hero_lich",
      denies: 1,
      totalGold: 39545,
      team: "DOTA_TEAM_GOODGUYS",
      heroDamage: 23464,
      totalExp: 33747,
      itemPurchases: {
        "0": "item_magic_stick",
        "1": "item_sobi_mask",
        "2": "item_branches",
        "3": "item_branches",
        "176": "item_boots",
        "186": "item_recipe_magic_wand",
        "243": "item_ring_of_health",
        "244": "item_cloak",
        "245": "item_ring_of_regen",
        "246": "item_recipe_hood_of_defiance",
        "247": "item_ring_of_regen",
        "248": "item_recipe_headdress",
        "258": "item_ward_sentry",
        "259": "item_ward_sentry",
        "291": "item_recipe_pog_pipe",
        "385": "item_point_booster",
        "424": "item_staff_of_wizardry",
        "425": "item_ogre_axe",
        "426": "item_blade_of_alacrity",
        "438": "item_ward_sentry",
        "439": "item_ward_sentry",
        "539": "item_recipe_woodland_striders",
        "655": "item_ring_of_health",
        "656": "item_void_stone",
        "657": "item_platemail",
        "658": "item_energy_booster",
        "832": "item_mystic_staff",
        "833": "item_vitality_booster",
        "834": "item_energy_booster",
        "835": "item_point_booster",
        "842": "item_mystic_staff",
        "843": "item_ultimate_orb",
        "844": "item_void_stone",
      },
      runesUsed: 0,
      abandoned: false,
      abilities: {
        lich_sinister_gaze: 4,
        ability_capture: 1,
        special_bonus_unique_lich_5: 1,
        generic_hidden: 0,
        special_bonus_unique_lich_1: 1,
        special_bonus_cast_range_150: 1,
        special_bonus_hp_150: 1,
        special_bonus_unique_lich_4: 1,
        special_bonus_movement_speed_15: 1,
        special_bonus_attack_damage_100: 1,
        special_bonus_unique_lich_3: 1,
        lich_chain_frost: 3,
        lich_frost_nova: 4,
        lich_frost_shield: 4,
      },
      finalInventory: {
        "0": "item_lotus_orb",
        "1": "item_pog_pipe",
        "2": "item_octarine_core",
        "3": "item_sheepstick",
        "4": "item_ultimate_scepter",
        "5": "item_woodland_striders",
      },
      steamid: "76561198026633444",
      healthDropDuration: 62.498413085938,
      tpScrollsUsed: 6,
      lastHits: 49,
      buildingDamage: 9324,
      level: 30,
      banChoice: "npc_dota_hero_storm_spirit",
      rerolledHeroes: ["npc_dota_hero_meepo"],
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 11357,
      neutralItems: 1,
      highFives: 0,
      healingGoblets: 9,
      deaths: 2,
      doubleKills: 0,
      kills: 12,
      username: "Iskander",
      rampages: 0,
      spentRerolls: 0,
    },
    "1": {
      assists: 13,
      availablePicks: [
        "npc_dota_hero_life_stealer",
        "npc_dota_hero_disruptor",
        "npc_dota_hero_zuus",
        "npc_dota_hero_tusk",
        "npc_dota_hero_obsidian_destroyer",
      ],
      finalPick: "npc_dota_hero_zuus",
      denies: 2,
      totalGold: 40685,
      team: "DOTA_TEAM_GOODGUYS",
      heroDamage: 42093,
      totalExp: 33510,
      itemPurchases: {
        "0": "item_ward_observer",
        "1": "item_branches",
        "2": "item_branches",
        "3": "item_magic_stick",
        "4": "item_sobi_mask",
        "59": "item_recipe_magic_wand",
        "110": "item_boots",
        "112": "item_recipe_ring_of_basilius",
        "116": "item_ward_sentry",
        "117": "item_ward_observer",
        "171": "item_energy_booster",
        "207": "item_void_stone",
        "256": "item_recipe_aether_lens",
        "272": "item_ward_observer",
        "273": "item_ward_sentry",
        "328": "item_ward_sentry",
        "334": "item_energy_booster",
        "370": "item_point_booster",
        "371": "item_staff_of_wizardry",
        "372": "item_ogre_axe",
        "419": "item_blade_of_alacrity",
        "447": "item_staff_of_wizardry",
        "448": "item_ring_of_regen",
        "450": "item_recipe_force_staff",
        "532": "item_mystic_staff",
        "533": "item_vitality_booster",
        "552": "item_energy_booster",
        "592": "item_point_booster",
        "647": "item_timeless_relic",
        "735": "item_boots",
        "791": "item_recipe_force_boots",
        "800": "item_staff_of_wizardry",
        "801": "item_robe",
        "802": "item_recipe_kaya",
        "805": "item_ogre_axe",
        "806": "item_belt_of_strength",
        "807": "item_recipe_sange",
        "820": "item_blade_of_alacrity",
        "821": "item_boots_of_elves",
        "822": "item_recipe_yasha",
        "904": "item_recipe_trident",
      },
      runesUsed: 0,
      abandoned: false,
      abilities: {
        ability_capture: 1,
        zuus_cloud: 1,
        zuus_lightning_bolt: 4,
        generic_hidden: 0,
        special_bonus_cast_range_225: 1,
        special_bonus_unique_zeus_2: 1,
        special_bonus_unique_zeus: 1,
        special_bonus_cooldown_reduction_12: 1,
        special_bonus_unique_zeus_3: 1,
        special_bonus_hp_200: 1,
        zuus_arc_lightning: 4,
        zuus_thundergods_wrath: 3,
        zuus_static_field: 4,
        special_bonus_mp_regen_2: 1,
        special_bonus_movement_speed_25: 1,
      },
      finalInventory: {
        "0": "item_force_boots",
        "1": "item_timeless_relic",
        "2": "item_trident",
        "3": "item_aether_lens",
        "4": "item_octarine_core",
        "5": "item_ultimate_scepter",
      },
      steamid: "76561197994993119",
      healthDropDuration: 28,
      tpScrollsUsed: 10,
      lastHits: 87,
      buildingDamage: 255,
      level: 30,
      banChoice: "npc_dota_hero_tinker",
      rerolledHeroes: ["npc_dota_hero_disruptor"],
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 6234,
      neutralItems: 3,
      highFives: 0,
      healingGoblets: 4,
      deaths: 1,
      doubleKills: 1,
      kills: 15,
      username: "Pyro!",
      rampages: 0,
      spentRerolls: 0,
    },
    "2": {
      assists: 16,
      availablePicks: [
        "npc_dota_hero_antimage",
        "npc_dota_hero_spirit_breaker",
        "npc_dota_hero_medusa",
        "npc_dota_hero_broodmother",
      ],
      finalPick: "npc_dota_hero_medusa",
      denies: 0,
      totalGold: 42721,
      team: "DOTA_TEAM_GOODGUYS",
      heroDamage: 18190,
      totalExp: 28205,
      itemPurchases: {
        "0": "item_sobi_mask",
        "1": "item_magic_stick",
        "2": "item_ward_sentry",
        "3": "item_ward_observer",
        "85": "item_boots",
        "173": "item_javelin",
        "282": "item_mithril_hammer",
        "308": "item_ogre_axe",
        "309": "item_boots_of_elves",
        "310": "item_boots_of_elves",
        "426": "item_staff_of_wizardry",
        "427": "item_robe",
        "428": "item_recipe_kaya",
        "429": "item_ogre_axe",
        "430": "item_belt_of_strength",
        "431": "item_recipe_sange",
        "451": "item_staff_of_wizardry",
        "452": "item_robe",
        "474": "item_recipe_kaya",
        "575": "item_recipe_trident",
        "659": "item_recipe_woodland_striders",
        "703": "item_ogre_axe",
        "704": "item_belt_of_strength",
        "718": "item_recipe_sange",
        "765": "item_blade_of_alacrity",
        "766": "item_boots_of_elves",
        "767": "item_recipe_yasha",
        "775": "item_hyperstone",
        "848": "item_relic",
        "849": "item_demon_edge",
        "863": "item_recipe_pog_mjollnir",
      },
      runesUsed: 0,
      abandoned: false,
      abilities: {
        medusa_split_shot: 4,
        special_bonus_evasion_15: 1,
        medusa_mana_shield: 4,
        ability_capture: 1,
        special_bonus_unique_medusa: 1,
        special_bonus_unique_medusa_4: 1,
        special_bonus_unique_medusa_5: 1,
        special_bonus_attack_damage_15: 1,
        special_bonus_attack_speed_30: 1,
        generic_hidden: 0,
        special_bonus_unique_medusa_3: 1,
        medusa_mystic_snake: 4,
        special_bonus_mp_800: 1,
        medusa_stone_gaze: 3,
      },
      finalInventory: {
        "0": "item_trident",
        "1": "item_kaya_and_sange",
        "2": "item_dragon_lance",
        "3": "item_pog_mjollnir",
        "4": "item_rapier",
        "5": "item_woodland_striders",
      },
      steamid: "76561198027875765",
      healthDropDuration: 138.69348144531,
      tpScrollsUsed: 6,
      lastHits: 233,
      buildingDamage: 1982,
      level: 30,
      banChoice: "npc_dota_hero_invoker",
      rerolledHeroes: [],
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 9283,
      neutralItems: 2,
      highFives: 0,
      healingGoblets: 22,
      deaths: 3,
      doubleKills: 1,
      kills: 4,
      username: "Nhea Samaye",
      rampages: 0,
      spentRerolls: 0,
    },
    "3": {
      assists: 5,
      availablePicks: [
        "npc_dota_hero_ancient_apparition",
        "npc_dota_hero_alchemist",
        "npc_dota_hero_jakiro",
        "npc_dota_hero_ogre_magi",
      ],
      finalPick: "npc_dota_hero_jakiro",
      denies: 0,
      totalGold: 20467,
      team: "DOTA_TEAM_BADGUYS",
      heroDamage: 23562,
      totalExp: 11810,
      itemPurchases: {
        "0": "item_magic_stick",
        "1": "item_branches",
        "2": "item_branches",
        "3": "item_recipe_magic_wand",
        "4": "item_ward_observer",
        "5": "item_ward_sentry",
        "6": "item_ward_sentry",
        "7": "item_ward_observer",
        "164": "item_sobi_mask",
        "165": "item_recipe_ring_of_basilius",
        "166": "item_crown",
        "167": "item_recipe_veil_of_discord",
        "168": "item_boots",
        "171": "item_ward_observer",
        "265": "item_staff_of_wizardry",
        "266": "item_ogre_axe",
        "357": "item_point_booster",
        "415": "item_blade_of_alacrity",
        "565": "item_timeless_relic",
        "747": "item_timeless_relic",
        "819": "item_timeless_relic",
      },
      runesUsed: 0,
      abandoned: false,
      abilities: {
        jakiro_ice_path: 4,
        special_bonus_spell_amplify_6: 1,
        jakiro_liquid_fire: 4,
        generic_hidden: 0,
        ability_capture: 1,
        special_bonus_unique_jakiro_2: 1,
        special_bonus_unique_jakiro: 0,
        special_bonus_unique_jakiro_5: 1,
        jakiro_dual_breath: 4,
        special_bonus_unique_jakiro_4: 0,
        special_bonus_attack_range_275: 0,
        special_bonus_unique_jakiro_3: 0,
        special_bonus_hp_275: 0,
        jakiro_macropyre: 3,
      },
      finalInventory: {
        "0": "item_boots",
        "1": "item_veil_of_discord",
        "2": "item_ultimate_scepter",
        "3": "item_timeless_relic",
        "4": "item_timeless_relic",
        "5": "item_timeless_relic",
      },
      steamid: "76561198088707423",
      healthDropDuration: 95.598876953125,
      tpScrollsUsed: 9,
      lastHits: 203,
      buildingDamage: 601,
      level: 24,
      banChoice: "npc_dota_hero_viper",
      rerolledHeroes: [],
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 1577,
      neutralItems: 3,
      highFives: 0,
      healingGoblets: 14,
      deaths: 11,
      doubleKills: 0,
      kills: 1,
      username: "Cholocate",
      rampages: 0,
      spentRerolls: 0,
    },
    "4": {
      assists: 4,
      availablePicks: [
        "npc_dota_hero_luna",
        "npc_dota_hero_furion",
        "npc_dota_hero_bounty_hunter",
        "npc_dota_hero_lone_druid",
      ],
      finalPick: "npc_dota_hero_luna",
      denies: 1,
      totalGold: 15862,
      team: "DOTA_TEAM_BADGUYS",
      heroDamage: 10189,
      totalExp: 10046,
      itemPurchases: {
        "0": "item_magic_stick",
        "1": "item_branches",
        "2": "item_branches",
        "3": "item_recipe_magic_wand",
        "144": "item_point_booster",
        "277": "item_staff_of_wizardry",
        "278": "item_ogre_axe",
        "279": "item_blade_of_alacrity",
        "358": "item_boots",
        "448": "item_gloves",
        "449": "item_belt_of_strength",
        "505": "item_ring_of_health",
        "506": "item_void_stone",
        "573": "item_ring_of_health",
        "574": "item_void_stone",
        "633": "item_recipe_refresher",
        "820": "item_timeless_relic",
      },
      runesUsed: 0,
      abandoned: false,
      abilities: {
        special_bonus_unique_luna_2: 1,
        luna_moon_glaive: 4,
        luna_lucent_beam: 4,
        generic_hidden: 0,
        special_bonus_attack_speed_15: 0,
        ability_capture: 1,
        special_bonus_cast_range_350: 1,
        special_bonus_unique_luna_5: 0,
        special_bonus_lifesteal_30: 0,
        luna_lunar_blessing: 4,
        special_bonus_all_stats_8: 1,
        luna_eclipse: 3,
        special_bonus_unique_luna_1: 0,
        special_bonus_movement_speed_25: 0,
      },
      finalInventory: {
        "0": "item_magic_wand",
        "1": "item_ultimate_scepter",
        "2": "item_power_treads",
        "3": "item_refresher",
        "4": "item_timeless_relic",
      },
      steamid: "76561198096660477",
      healthDropDuration: 63,
      tpScrollsUsed: 8,
      lastHits: 43,
      buildingDamage: 806,
      level: 24,
      banChoice: "npc_dota_hero_lina",
      rerolledHeroes: [],
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 1912,
      neutralItems: 1,
      highFives: 0,
      healingGoblets: 10,
      deaths: 10,
      doubleKills: 0,
      kills: 0,
      username: "Saint",
      rampages: 0,
      spentRerolls: 0,
    },
    "5": {
      assists: 0,
      availablePicks: [
        "npc_dota_hero_chen",
        "npc_dota_hero_riki",
        "npc_dota_hero_enchantress",
        "npc_dota_hero_gyrocopter",
        "npc_dota_hero_naga_siren",
      ],
      finalPick: "npc_dota_hero_riki",
      denies: 0,
      totalGold: 16744,
      team: "DOTA_TEAM_BADGUYS",
      heroDamage: 13530,
      totalExp: 16903,
      itemPurchases: {
        "0": "item_magic_stick",
        "1": "item_branches",
        "2": "item_branches",
        "3": "item_recipe_magic_wand",
        "4": "item_branches",
        "5": "item_branches",
        "6": "item_branches",
        "152": "item_blade_of_alacrity",
        "178": "item_blade_of_alacrity",
        "179": "item_robe",
        "231": "item_recipe_diffusal_blade",
        "244": "item_ward_sentry",
        "331": "item_broadsword",
        "398": "item_mithril_hammer",
        "461": "item_ring_of_health",
        "462": "item_void_stone",
        "463": "item_quelling_blade",
        "529": "item_ward_sentry",
        "530": "item_ward_sentry",
        "608": "item_mithril_hammer",
        "652": "item_belt_of_strength",
        "653": "item_recipe_basher",
        "672": "item_ring_of_health",
        "717": "item_vitality_booster",
        "804": "item_recipe_abyssal_blade",
      },
      runesUsed: 1,
      abandoned: false,
      abilities: {
        special_bonus_attack_damage_20: 1,
        riki_backstab: 3,
        special_bonus_unique_riki_1: 1,
        generic_hidden: 0,
        special_bonus_hp_regen_6: 0,
        ability_capture: 1,
        riki_tricks_of_the_trade: 4,
        special_bonus_unique_riki_7: 0,
        special_bonus_unique_riki_2: 0,
        riki_smoke_screen: 4,
        special_bonus_unique_riki_6: 1,
        special_bonus_attack_speed_20: 1,
        special_bonus_unique_riki_3: 0,
        riki_blink_strike: 4,
      },
      finalInventory: {
        "0": "item_diffusal_blade",
        "1": "item_magic_wand",
        "2": "item_abyssal_blade",
        "3": "item_bfury",
        "5": "item_branches",
        "6": "item_branches",
        "7": "item_branches",
      },
      steamid: "76561198049688174",
      healthDropDuration: 55.864990234375,
      tpScrollsUsed: 8,
      lastHits: 37,
      buildingDamage: 1471,
      level: 25,
      banChoice: "npc_dota_hero_phantom_assassin",
      rerolledHeroes: ["npc_dota_hero_chen"],
      permanentBuffs: [],
      disconnectEvents: [],
      heroHealing: 0,
      currentGold: 2344,
      neutralItems: 0,
      highFives: 0,
      healingGoblets: 9,
      deaths: 10,
      doubleKills: 0,
      kills: 5,
      username: "TM 41",
      rampages: 0,
      spentRerolls: 0,
    },
  },
  cheatsEnabled: false,
  bannedHeroes: [
    "npc_dota_hero_viper",
    "npc_dota_hero_storm_spirit",
    "npc_dota_hero_tinker",
    "npc_dota_hero_invoker",
    "npc_dota_hero_phantom_assassin",
    "npc_dota_hero_lina",
  ],
  rankedGame: true,
};

function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min)) + min;
}

function randomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function getRandomFromBucket(bucket) {
  const randomIndex = Math.floor(Math.random() * bucket.length);
  return bucket.splice(randomIndex, 1)[0];
}

const heroes = [
  "npc_dota_hero_antimage",
  "npc_dota_hero_batrider",
  "npc_dota_hero_keeper_of_the_light",
  "npc_dota_hero_lina",
  "npc_dota_hero_slark",
  "npc_dota_hero_zuus",
  // "npc_dota_hero_scaldris",
];

const steamIDs = [
  "76561197960956468",
  "76561197964547457",
  "76561198014254115",
  "76561197960287930",
  "76561198052211234",
  "76561198015161808",
  "76561198007141460",
  "76561198030851434",
];

const usernames = {
  "76561197960956468": "HIPPOcrit",
  "76561197964547457": "DC | @syndereNDota",
  "76561198014254115": "IceFrog",
  "76561197960287930": "Rabscuttle",
  "76561198052211234": "bukka",
  "76561198015161808": "EarthSalamander",
  "76561198007141460": "Firetoad",
  "76561198030851434": "VicFrank",
};

function generateTeamInfo() {
  let teamInfo = {};
  teamInfo.kills = randomInt(0, 100).toString();
  teamInfo.deaths = randomInt(0, 100).toString();
  teamInfo.assists = randomInt(0, 100).toString();
  if (randomInt(0, 10) < 5) {
    teamInfo.guardianKills = {};
    teamInfo.guardianKills[randomInt(100, 1000)] = "POG_GUARDIAN_CREEPS";
    teamInfo.guardianKills[randomInt(100, 1000)] = "POG_GUARDIAN_DAMAGE";
    teamInfo.guardianKills[randomInt(100, 1000)] = "POG_GUARDIAN_CDR";
  }
  if (randomInt(0, 10) < 9) {
    teamInfo.buildingKills = {};
    teamInfo.buildingKills.firstTower = randomInt(100, 2000).toString();
    teamInfo.buildingKills.secondTower = randomInt(100, 2000).toString();
    teamInfo.buildingKills.barracks = randomInt(100, 2000).toString();
    teamInfo.buildingKills.thirdTower = randomInt(100, 2000).toString();
    teamInfo.buildingKills.fourthTower = randomInt(100, 2000).toString();
  }

  return teamInfo;
}

function generatePlayerInfo(steamIDBucket, team) {
  let playerInfo = {};
  playerInfo.steamid = getRandomFromBucket(steamIDBucket);
  playerInfo.team = team;
  playerInfo.username = usernames[playerInfo.steamid];
  if (randomInt(0, 10) < 5) {
    playerInfo.banChoice = randomElement(heroes);
  }
  playerInfo.availablePicks = [];
  playerInfo.availablePicks.push(randomElement(heroes));
  playerInfo.availablePicks.push(randomElement(heroes));
  playerInfo.availablePicks.push(randomElement(heroes));
  if (randomInt(0, 10) < 8) {
    playerInfo.rerolledHeroes = [];
    playerInfo.rerolledHeroes.push(randomElement(heroes));
  }
  playerInfo.finalPick = randomElement(heroes);
  playerInfo.kills = randomInt(0, 50).toString();
  playerInfo.deaths = randomInt(0, 50).toString();
  playerInfo.assists = randomInt(0, 50).toString();
  playerInfo.lastHits = randomInt(0, 300).toString();
  playerInfo.denies = randomInt(0, 100).toString();
  playerInfo.currentGold = randomInt(0, 999).toString();
  playerInfo.doubleKills = randomInt(0, 8).toString();
  playerInfo.rampages = randomInt(0, 2).toString();
  playerInfo.heroDamage = randomInt(0, 50000).toString();
  playerInfo.buildingDamage = randomInt(0, 50000).toString();
  playerInfo.heroHealing = randomInt(0, 1000).toString();
  playerInfo.tpScrollsUsed = randomInt(0, 10).toString();
  playerInfo.runesUsed = randomInt(0, 10).toString();
  playerInfo.healthDropDuration = randomInt(0, 100).toString();
  playerInfo.totalGold = randomInt(1000, 10000).toString();
  playerInfo.totalExp = randomInt(1000, 10000).toString();
  playerInfo.level = randomInt(1, 25).toString();
  playerInfo.spentRerolls = randomInt(0, 3).toString();
  playerInfo.neutralItems = randomInt(0, 3).toString();
  playerInfo.healingGoblets = randomInt(0, 3).toString();
  playerInfo.highFives = randomInt(0, 3).toString();

  playerInfo.abilities = {
    lina_dragon_slave: "4",
    lina_light_strike_array: "4",
    lina_fiery_soul: "4",
    lina_laguna_blade: "3",
    special_ability_damage_30: "1",
    special_ability_spell_amp_12: "1",
    special_ability_mana_regen_3: "1",
  };

  playerInfo.finalInventory = {
    "0": "item_blink",
    "1": "item_cyclone",
    "2": "item_sheepstick",
    "3": "item_phase_boots",
    "4": "item_nokrash_blade",
    "5": "item_sphere",
    "6": "item_mango",
    "7": "item_refresher",
  };

  playerInfo.itemPurchases = {
    "34": "item_blink",
    "42": "item_cyclone",
    "111": "item_sheepstick",
    "234": "item_phase_boots",
    "456": "item_nokrash_blade",
    "799": "item_sphere",
    "919": "item_mango",
    "1028": "item_refresher",
  };

  if (randomInt(0, 10) < 5) {
    playerInfo.permanentBuffs = [
      "modifier_moon_shard_consumed",
      "modifier_ultimate_scepter_consumed",
    ];
  }

  if (randomInt(0, 10) < 8) {
    playerInfo.disconnectEvents = {
      "37": "45",
      "871": "-1",
    };
  }

  return playerInfo;
}

const generateRandomSampleData = () => {
  let gameStats = {};
  gameStats.gameDuration = randomInt(3000, 6000);
  gameStats.cheatsEnabled = randomElement(["true", "false"]);
  gameStats.rankedGame = randomElement(["true", "false"]);
  gameStats.winnerTeam = randomElement([
    "DOTA_TEAM_GOODGUYS",
    "DOTA_TEAM_BADGUYS",
  ]);
  gameStats.healthDrops = randomInt(0, 100).toString();
  gameStats.bannedHeroes = [];
  for (let i = 0; i < randomInt(0, 6); i++) {
    gameStats.bannedHeroes.push(randomElement(heroes));
  }
  gameStats.teamInfo = {};
  gameStats.teamInfo.DOTA_TEAM_GOODGUYS = generateTeamInfo();
  gameStats.teamInfo.DOTA_TEAM_BADGUYS = generateTeamInfo();

  gameStats.playerInfo = [];
  let steamIDBucket = [...steamIDs];
  for (let i = 0; i < 3; i++) {
    gameStats.playerInfo[i.toString()] = generatePlayerInfo(
      steamIDBucket,
      "DOTA_TEAM_GOODGUYS"
    );
    gameStats.playerInfo[(i + 3).toString()] = generatePlayerInfo(
      steamIDBucket,
      "DOTA_TEAM_BADGUYS"
    );
  }

  return gameStats;
};

module.exports = {
  sampleData,
  realSample,
  testSample,
  generateRandomSampleData,
};
