export default {
  chest1: [
    "[Guaranteed] A random Common item!",
    "[Guaranteed] Up to 125 Poggers!",
    "[Chance] A bonus Uncommon item",
    "[Small Chance] A bonus Rare item",
  ],
  chest2: [
    "[Guaranteed] A random Uncommon item!",
    "[Guaranteed] Up to 250 Poggers!",
    "[High chance] A bonus random Common item",
    "[Chance] A bonus Rare item",
    "[Small Chance] A bonus Mythical item",
  ],
  chest3: [
    "[Guaranteed] A random Mythical item!",
    "[Guaranteed] Up to 450 Poggers!",
    "[High chance] A bonus random Common item",
    "[High chance] A bonus random Uncommon item",
    "[Chance] A bonus Mythical item",
    "[Very Small Chance] A bonus legendary item!",
  ],
  chest4: [
    "[Guaranteed] A random Mythical item!",
    "[Guaranteed] Up to 1100 Poggers!",
    "[Chance] Up to 10,000 bonus battle pass exp!",
    "[Guaranteed] A bonus Common item",
    "[High chance] A bonus random Uncommon item",
    "[High chance] A bonus random Rare item",
    "[Chance] A bonus Mythical item",
    "[Small Chance] A bonus Legendary item",
    "[Very Small Chance] The unique Overgrown Emblem!",
  ],
  chest5: [
    "[Guaranteed] A random Legendary item!",
    "[Guaranteed] Up to 2000 Poggers!",
    "[Guaranteed] A bonus Common item",
    "[Guaranteed] A bonus Uncommon item",
    "[Guaranteed] A bonus Rare item",
    "[Chance] A bonus Mythical item",
  ],
};
