export default {
  chest1: [
    "Contains 1 random Common item",
    "Contains 5-150 POGGERS",
    "May contain up to 2,000 battlepass experience",
    "May contain 1 bonus Uncommon item",
    "[Very Rare] May contain 1 bonus Rare item",
  ],
  chest2: [
    "Contains 1 random Uncommon item",
    "Contains 10-300 POGGERS",
    "May contain up to 5,000 battlepass experience",
    "May contain 1 bonus Rare item",
    "[Very Rare] May contain 1 bonus Mythical item",
  ],
  chest3: [
    "Contains 1 random Rare item",
    "Contains 25-600 POGGERS",
    "May contain up to 10,000 battlepass experience",
    "May contain 1 bonus Mythical item",
    "[Very Rare] May contain 1 bonus Legendary item",
  ],
  chest4: [
    "Contains 1 random Mythical item",
    "Contains 60-1500 POGGERS",
    "May contain up to 25,000 battlepass experience",
    "May contain 1 bonus Mythical item",
    "May contain 1 bonus Legendary item",
  ],
  chest5: [
    "Contains 1 random Legendary item",
    "Contains 150-3000 POGGERS",
    "May contain up to 25,000 battlepass experience",
    "May contain 1 bonus Mythical item",
    "May contain 1 bonus Legendary item",
    "[Ultra Rare] May contain 1 bonus Ultra Rare special companion",
  ],
  announcer1:
    "Congratulations! Whether you want it or not, you now own the greatest Announcer Pack ever created, voiced by the wise yet sometimes senile Old Man Gilly Winkle.",
  border1: "Uncommon Avatar Border",
  border2: "Rare Avatar Border",
  border3: "Mythical Avatar Border",
  border4: "Legendary Avatar Border",
  border5: "Ancient Avatar Border",
  badge1: "Bronze Badge for your profile",
  badge2: "Silver Badge for your profile",
  badge3: "Gold Badge for your profile",
  badge4: "Platinum Badge for your profile",
  badge5: "Royal Badge for your profile",
  picking1: "Unlock a 4th hero slot in the pick screen",
  reroll: "Unlock an additional Re-roll in the pick screen (22 hour cooldown)",
  reroll1: "Unlock an additional Re-roll in the pick screen (22 hour cooldown)",
  reroll2: "Unlock an additional Re-roll in the pick screen (22 hour cooldown)",
  bpaccel1: [
    "1 month of the following XP perks: ",
    "+100% Battlepass experience gain from matches",
    "+50% experience on your first win of the day",
  ],
  bpaccel2: [
    "1 month of the following XP perks:",
    "+300% Battlepass experience gain from matches",
    "+100% experience on your first win of the day",
  ],
  xp_coupon_500: "500 XP",
  xp_coupon_1000: "1000 XP",
  xp_coupon_2000: "2000 XP",
  xp_coupon_5000: "5000 XP",
  xp_coupon_10000: "10,000 XP",
  xp_coupon_25000: "25,000 XP",
};
