const cosmeticsData = {
  announcer1: "Old Man Gilly Winkle Announcer Pack",
  border1: "Avatar Border 1",
  border2: "Avatar Border 2",
  border3: "Avatar Border 3",
  border4: "Avatar Border 4",
  badge1: "Player Badge 1",
  badge2: "Player Badge 2",
  badge3: "Player Badge 3",
  badge4: "Player Badge 4",
  badge5: "Player Badge 5",
  assault1: "Assault Cuirass Aura 1",
  assault2: "Assault Cuirass Aura 2",
  assault3: "Assault Cuirass Aura 3",
  blink1: "Blink Dagger FX 1",
  blink2: "Blink Dagger FX 2",
  blink3: "Blink Dagger FX 3",
  deny1: "Deny FX 1",
  deny2: "Deny FX 2",
  deny3: "Deny FX 3",
  deny4: "Deny FX 4",
  deny5: "Deny FX 5",
  cyclone1: "Eul FX 1",
  cyclone2: "Eul FX 2",
  cyclone3: "Eul FX 3",
  force1: "Force Staff FX 1",
  force2: "Force Staff FX 2",
  force3: "Force Staff FX 3",
  fountain1: "Fountain FX 1",
  fountain2: "Fountain FX 2",
  fountain3: "Fountain FX 3",
  greaves1: "Greaves Aura 1",
  greaves2: "Greaves Aura 2",
  greaves3: "Greaves Aura 3",
  levelup1: "Level Up FX 1",
  levelup2: "Level Up FX 2",
  levelup3: "Level Up FX 3",
  mek1: "Mekansm FX 1",
  mek2: "Mekansm FX 2",
  mek3: "Mekansm FX 3",
  mjollnir1: "Mjollnir FX 1",
  mjollnir2: "Mjollnir FX 2",
  mjollnir3: "Mjollnir FX 3",
  picking1: "Extra Picking Slot 1",
  picking2: "Extra Picking Slot 2",
  phase1: "Phase Boots FX 1",
  phase2: "Phase Boots FX 2",
  phase3: "Phase Boots FX 3",
  pipe1: "Pipe Aura 1",
  pipe2: "Pipe Aura 2",
  pipe3: "Pipe Aura 3",
  radiance1: "Radiance FX 1",
  radiance2: "Radiance FX 2",
  radiance3: "Radiance FX 3",
  shiva1: "Shivas FX 1",
  shiva2: "Shivas FX 2",
  shiva3: "Shivas FX 3",
  shivaaura1: "Shivas Aura 1",
  shivaaura2: "Shivas Aura 2",
  shivaaura3: "Shivas Aura 3",
  teleport1: "Teleport FX 1",
  teleport2: "Teleport FX 2",
  teleport3: "Teleport FX 3",
  vlads1: "Vlads Aura 1",
  vlads2: "Vlads Aura 2",
  vlads3: "Vlads Aura 3",
  highfive1: "High Five 1",
  highfive2: "High Five 2",
  highfive3: "High Five 3",
  highfive4: "High Five 4",
  highfive5: "High Five 5",
  baloon1: "Balloon 1",
  baloon2: "Balloon 2",
  baloon3: "Balloon 3",
  baloon4: "Balloon 4",
  baloon5: "Balloon 5",
  baloon6: "Balloon 6",
  baloon7: "Balloon 7",
  baloon8: "Balloon 8",
  baloon9: "Balloon 9",
  baloon10: "Balloon 10",
  bpaccel1: "Silver Battlepass Accelerator",
  bpaccel2: "Golden Battlepass Accelerator",
  chest1: "Common Chest",
  chest2: "Uncommon Chest",
  chest3: "Rare Chest",
  chest4: "Mythical Chest",
  chest5: "Legendary Chest",
  companion1: "Carty",
  companion2: "Cluckles",
  companion3: "Doomling",
  companion4: "Huntling",
  companion5: "Turbo the Turtle",
  companion6: "Itsy",
  companion7: "Krobeling",
  companion8: "Mighty Boar",
  companion9: "Shroom Hat",
  companion10: "Llama the Llama",
  companion11: "Venoling",
  companion12: "Choppy the Log Surfer",
  companion13: "Cate & Doge",
  companion14: "Icefrog",
  companion15: "Demon Intern",
  companion16: "Angelic Recruit",
  companion17: "Nian the Cuddle Beast",
  companion18: "Butch",
  companion19: "Drodo the Druffin",
  companion20: "Pangoling",
  companion21: "Scotty",
  companion22: "Tory the Sky Guardian",
  companion23: "Landshark",
  companion24: "Janjou the Brave",
  companion25: "Greevil",
  companion26: "Pudgling",
  companion27: "Shagbark",
  companion28: "Parasight",
  companion29: "Tory",
  companionfx1: "Affliction of Vermin",
  companionfx2: "Butterfly Romp",
  companionfx3: "Felicity's Blessing",
  companionfx4: "New Bloom Celebration",
  companionfx5: "Orbital Decay",
  companionfx6: "Searing Essence",
  companionfx7: "Spirit of Earth",
  companionfx8: "Spirit of Ember",
  companionfx9: "Touch of Midas",
  companionfx10: "Triumph of Champions",
  companionfx11: "Bleak Hallucination",
  companionfx12: "Crystal Rift",
  companionfx13: "Frostivus Frost",
  companionfx14: "Ionic Vapor",
  companionfx15: "Trail of the Lotus Blossom",
  companionfx16: "Ocean's Call",
  companionfx17: "Champion's Aura 2014",
  companionfx18: "Ethereal Flame",
  companionfx19: "Star Blaze",
  companionfx20: "Trail of Burning Doom",
};

export default cosmeticsData;
