const cosmeticsData = {
  announcer1: "Old Man Gilly Winkle Announcer Pack",
  border1: "Avatar Border 1",
  border2: "Avatar Border 2",
  border3: "Avatar Border 3",
  border4: "Avatar Border 4",
  badge1: "Player Badge 1",
  badge2: "Player Badge 2",
  badge3: "Player Badge 3",
  badge4: "Player Badge 4",
  badge5: "Player Badge 5",
  assault1: "Assault Cuirass Aura 1",
  assault2: "Assault Cuirass Aura 2",
  assault3: "Assault Cuirass Aura 3",
  blink1: "Blink Dagger FX 1",
  blink2: "Blink Dagger FX 2",
  blink3: "Blink Dagger FX 3",
  deny1: "Deny FX 1",
  deny2: "Deny FX 2",
  deny3: "Deny FX 3",
  deny4: "Deny FX 4",
  deny5: "Deny FX 5",
  cyclone1: "Eul FX 1",
  cyclone2: "Eul FX 2",
  cyclone3: "Eul FX 3",
  force1: "Force Staff FX 1",
  force2: "Force Staff FX 2",
  force3: "Force Staff FX 3",
  fountain1: "Fountain FX 1",
  fountain2: "Fountain FX 2",
  fountain3: "Fountain FX 3",
  greaves1: "Greaves Aura 1",
  greaves2: "Greaves Aura 2",
  greaves3: "Greaves Aura 3",
  levelup1: "Level Up FX 1",
  levelup2: "Level Up FX 2",
  levelup3: "Level Up FX 3",
  mek1: "Mekansm FX 1",
  mek2: "Mekansm FX 2",
  mek3: "Mekansm FX 3",
  mjollnir1: "Mjollnir FX 1",
  mjollnir2: "Mjollnir FX 2",
  mjollnir3: "Mjollnir FX 3",
  picking1: "Extra Picking Slot 1",
  picking2: "Extra Picking Slot 2",
  phase1: "Phase Boots FX 1",
  phase2: "Phase Boots FX 2",
  phase3: "Phase Boots FX 3",
  pipe1: "Pipe Aura 1",
  pipe2: "Pipe Aura 2",
  pipe3: "Pipe Aura 3",
  radiance1: "Radiance FX 1",
  radiance2: "Radiance FX 2",
  radiance3: "Radiance FX 3",
  shiva1: "Shivas FX 1",
  shiva2: "Shivas FX 2",
  shiva3: "Shivas FX 3",
  shivaaura1: "Shivas Aura 1",
  shivaaura2: "Shivas Aura 2",
  shivaaura3: "Shivas Aura 3",
  teleport1: "Teleport FX 1",
  teleport2: "Teleport FX 2",
  teleport3: "Teleport FX 3",
  vlads1: "Vlads Aura 1",
  vlads2: "Vlads Aura 2",
  vlads3: "Vlads Aura 3",
  highfive1: "High Five 1",
  highfive2: "High Five 2",
  highfive3: "High Five 3",
  highfive4: "High Five 4",
  highfive5: "High Five 5",
  baloon1: "Balloon 1",
  baloon2: "Balloon 2",
  baloon3: "Balloon 3",
  baloon4: "Balloon 4",
  baloon5: "Balloon 5",
  baloon6: "Balloon 6",
  baloon7: "Balloon 7",
  baloon8: "Balloon 8",
  baloon9: "Balloon 9",
  baloon10: "Balloon 10",
  bpaccel1: "Silver Battlepass Accelerator",
  bpaccel2: "Golden Battlepass Accelerator",
  chest1: "Common Chest",
  chest2: "Uncommon Chest",
  chest3: "Rare Chest",
  chest4: "Mythical Chest",
  chest5: "Legendary Chest",
  choppy_the_log_surfer: "Choppy The Log Surfer",
  cluckles_the_brave: "Cluckles The Brave",
  doomling: "Doomling",
  huntling: "Huntling",
  itsy: "Itsy",
  krobeling: "Krobeling",
  llama_the_llama: "Llama The Llama",
  mighty_boar: "Mighty Boar",
  shroom_hat: "Shroom Hat",
  turbo_the_turtle: "Turbo The Turtle",
  venoling: "Venoling",
  greevil: "Greevil",
  janjou: "Janjou",
  landshark: "Landshark",
  parasight: "Parasight",
  pudgling: "Pudgling",
  shagbark_the_plush: "Shagbark The Plush",
  tory: "Tory",
  butch: "Butch",
  drodo: "Drodo",
  tenderfoot: "Tenderfoot",
  scotty: "Scotty",
  tory_the_sky_guardian: "Tory The Sky Guardian",
  angelic_recruit: "Angelic Recruit",
  demon_intern: "Demon Intern",
  nian_the_cuddle_beast: "Nian The Cuddle Beast",
  baby_roshan: "Baby Roshan",
  icefrog: "Icefrog",
  carty: "Carty",
  spring_haze: "Spring Haze",
  butterfly_romp: "Butterfly Romp",
  felicitys_blessing: "Felicitys Blessing",
  acid_mist: "Acid Mist",
  orbital_decay: "Orbital Decay",
  searing_essence: "Searing Essence",
  winds_of_winter: "Winds Of Winter",
  spirit_of_ember: "Spirit Of Ember",
  touch_of_midas: "Touch Of Midas",
  silver_streak: "Silver Streak",
  bleak_hallucination: "Bleak Hallucination",
  crystal_rift: "Crystal Rift",
  frostivus_frost: "Frostivus Frost",
  desert_storm: "Desert Storm",
  trail_of_the_lotus_blossom: "Trail Of The Lotus Blossom",
  oceans_call: "Oceans Call",
  champions_aura_2014: "Champions Aura 2014",
  ethereal_flame: "Ethereal Flame",
  star_blaze: "Star Blaze",
  trail_of_burning_doom: "Trail Of Burning Doom",
  reroll: "Reroll",
  reroll1: "Plus 1 Daily Re-Roll Token",
  reroll2: "Plus 1 Daily Re-Roll Token",
};

export default cosmeticsData;
