const rewards = [
  {
    level: 1,
    item: "Bronze Badge",
    item_image: "badge_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 2,
    item: "High Five 1",
    item_image: "",
    chest_type: "Common",
    chest_amount: 1,
  },
  {
    level: 3,
    item: "Fountain FX 1",
    item_image: "Fountain_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 4,
    item: "",
    item_image: "",
    chest_type: "Common",
    chest_amount: 1,
  },
  {
    level: 5,
    item: "Level up FX 1",
    item_image: "level_up",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 6,
    item: "Deny FX 1",
    item_image: "deny",
    chest_type: "Common",
    chest_amount: 1,
  },
  {
    level: 7,
    item: "Blink FX 1",
    item_image: "Blink_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 8,
    item: "Balloon 1",
    item_image: "",
    chest_type: "Common",
    chest_amount: 1,
  },
  {
    level: 9,
    item: "",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 10,
    item: "Avatar Border 1",
    item_image: "avatar_border_1",
    chest_type: "Rare",
    chest_amount: 1,
  },
  {
    level: 11,
    item: "",
    item_image: "",
    chest_type: "Common",
    chest_amount: 1,
  },
  {
    level: 12,
    item: "Force Staff FX 1",
    item_image: "force_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 13,
    item: "",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 14,
    item: "Phase Boots FX 1",
    item_image: "phase_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 15,
    item: "",
    item_image: "",
    chest_type: "Common",
    chest_amount: 1,
  },
  {
    level: 16,
    item: "Fountain FX 2",
    item_image: "Fountain_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 17,
    item: "",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 18,
    item: "Mekansm / greaves FX 1",
    item_image: "mek_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 19,
    item: "High Five 2",
    item_image: "",
    chest_type: "Common",
    chest_amount: 1,
  },
  {
    level: 20,
    item: "Balloon 2",
    item_image: "",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 21,
    item: "Plus 1 Daily Re-Roll Token",
    item_image: "reroll",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 22,
    item: "Level up FX 2",
    item_image: "level_up",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 23,
    item: "Blink FX 2",
    item_image: "Blink_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 24,
    item: "",
    item_image: "",
    chest_type: "Common",
    chest_amount: 1,
  },
  {
    level: 25,
    item: "Silver Badge",
    item_image: "badge_2",
    chest_type: "Rare",
    chest_amount: 1,
  },
  {
    level: 26,
    item: "Balloon 3",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 27,
    item: "Radiance FX 1",
    item_image: "radiance_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 28,
    item: "Euls FX 1",
    item_image: "eul_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 29,
    item: "",
    item_image: "",
    chest_type: "Common",
    chest_amount: 1,
  },
  {
    level: 30,
    item: "Avatar Border 2",
    item_image: "avatar_border_2",
    chest_type: "Uncommon",
    chest_amount: 2,
  },
  {
    level: 31,
    item: "Deny FX 2",
    item_image: "deny",
    chest_type: "Common",
    chest_amount: 1,
  },
  {
    level: 32,
    item: "Maelstrom / Mjollnir FX 1",
    item_image: "Mjollnir_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 33,
    item: "Shiva's FX 1",
    item_image: "shiva_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 34,
    item: "",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 35,
    item: "Vladmir Aura FX 1",
    item_image: "vlad_aura_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 36,
    item: "High Five 3",
    item_image: "",
    chest_type: "Common",
    chest_amount: 2,
  },
  {
    level: 37,
    item: "Force Staff FX 2",
    item_image: "force_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 38,
    item: "Phase Boots FX 2",
    item_image: "phase_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 39,
    item: "Balloon 4",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 40,
    item: "Earn +1 Picking Slot",
    item_image: "Permanent_Extra_Picking_Slot",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 41,
    item: "",
    item_image: "",
    chest_type: "Rare",
    chest_amount: 1,
  },
  {
    level: 42,
    item: "Mekansm / Greaves FX 2",
    item_image: "mek_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 43,
    item: "Pipe Aura FX 1",
    item_image: "pipe_aura_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 44,
    item: "",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 45,
    item: "Deny FX 3",
    item_image: "deny",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 46,
    item: "",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 47,
    item: "Radiance FX 2",
    item_image: "radiance_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 48,
    item: "Shivas Aura FX 1",
    item_image: "shiva_aura_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 49,
    item: "Balloon 5",
    item_image: "",
    chest_type: "Common",
    chest_amount: 2,
  },
  {
    level: 50,
    item: "Avatar Border 3",
    item_image: "avatar_border_3",
    chest_type: "Mythical",
    chest_amount: 1,
  },
  {
    level: 51,
    item: "",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 52,
    item: "Euls FX 2",
    item_image: "eul_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 53,
    item: "Greaves Aura FX 1",
    item_image: "greaves_aura_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 54,
    item: "High Five 4",
    item_image: "",
    chest_type: "Common",
    chest_amount: 2,
  },
  {
    level: 55,
    item: "Gold Badge",
    item_image: "badge_3",
    chest_type: "Rare",
    chest_amount: 1,
  },
  {
    level: 56,
    item: "",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 1,
  },
  {
    level: 57,
    item: "Maelstrom / Mjollnir FX 2",
    item_image: "Mjollnir_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 58,
    item: "AC Aura FX 1",
    item_image: "assault_cuirass_1",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 59,
    item: "Balloon 6",
    item_image: "",
    chest_type: "Common",
    chest_amount: 3,
  },
  {
    level: 60,
    item: "Fountain FX 3",
    item_image: "Fountain_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 61,
    item: "",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 2,
  },
  {
    level: 62,
    item: "Shivas FX 2",
    item_image: "shiva_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 63,
    item: "Teleport FX 3",
    item_image: "teleport_scroll_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 64,
    item: "",
    item_image: "",
    chest_type: "Common",
    chest_amount: 3,
  },
  {
    level: 65,
    item: "Vladmir Aura FX 2",
    item_image: "vlad_aura_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 66,
    item: "Plus 1 Daily Re-Roll Token",
    item_image: "reroll",
    chest_type: "Uncommon",
    chest_amount: 2,
  },
  {
    level: 67,
    item: "Blink FX 3",
    item_image: "Blink_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 68,
    item: "Pipe Aura FX 2",
    item_image: "pipe_aura_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 69,
    item: "",
    item_image: "",
    chest_type: "Common",
    chest_amount: 3,
  },
  {
    level: 70,
    item: "Avatar Border 4",
    item_image: "avatar_border_4",
    chest_type: "Rare",
    chest_amount: 2,
  },
  {
    level: 71,
    item: "Balloon 7",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 2,
  },
  {
    level: 72,
    item: "Force Staff FX 3",
    item_image: "force_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 73,
    item: "Phase Boots FX 3",
    item_image: "phase_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 74,
    item: "Shivas Aura FX 2",
    item_image: "shiva_aura_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 75,
    item: "Platinum Badge",
    item_image: "badge_4",
    chest_type: "Rare",
    chest_amount: 1,
  },
  {
    level: 76,
    item: "",
    item_image: "",
    chest_type: "Common",
    chest_amount: 3,
  },
  {
    level: 77,
    item: "Mekansm/Greaves FX 3",
    item_image: "mek_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 78,
    item: "Radiance FX 3",
    item_image: "radiance_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 79,
    item: "Greaves Aura FX 2",
    item_image: "greaves_aura_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 80,
    item: "Balloon 8",
    item_image: "",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 81,
    item: "High Five 5",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 2,
  },
  {
    level: 82,
    item: "Maelstrom/Mjollnir FX 3",
    item_image: "Mjollnir_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 83,
    item: "Shivas FX 3",
    item_image: "shiva_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 84,
    item: "AC Aura FX 2",
    item_image: "assault_cuirass_2",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 85,
    item: "Deny FX 4",
    item_image: "deny",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 86,
    item: "",
    item_image: "",
    chest_type: "Uncommon",
    chest_amount: 3,
  },
  {
    level: 87,
    item: "Vladmir Aura FX 3",
    item_image: "vlad_aura_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 88,
    item: "Pipe Aura FX 3",
    item_image: "pipe_aura_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 89,
    item: "",
    item_image: "",
    chest_type: "Common",
    chest_amount: 5,
  },
  {
    level: 90,
    item: "Avatar Border 5",
    item_image: "avatar_border_4",
    chest_type: "Rare",
    chest_amount: 2,
  },
  {
    level: 91,
    item: "Balloon 9",
    item_image: "",
    chest_type: "Rare",
    chest_amount: 1,
  },
  {
    level: 92,
    item: "Shivas Aura FX 3",
    item_image: "shiva_aura_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 93,
    item: "",
    item_image: "",
    chest_type: "Rare",
    chest_amount: 1,
  },
  {
    level: 94,
    item: "Greaves Aura FX 3",
    item_image: "greaves_aura_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 95,
    item: "",
    item_image: "",
    chest_type: "Mythical",
    chest_amount: 1,
  },
  {
    level: 96,
    item: "AC Aura FX 3",
    item_image: "assault_cuirass_3",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 97,
    item: "Plus 1 Daily Re-Roll Token",
    item_image: "reroll",
    chest_type: "Rare",
    chest_amount: 1,
  },
  {
    level: 98,
    item: "Deny FX 5",
    item_image: "deny",
    chest_type: "",
    chest_amount: 0,
  },
  {
    level: 99,
    item: "Balloon 10",
    item_image: "",
    chest_type: "Rare",
    chest_amount: 1,
  },
  {
    level: 100,
    item: "Royal Badge",
    item_image: "badge_5",
    chest_type: "Legendary",
    chest_amount: 1,
  },
];

export default rewards;
